# Site settings
title: Data Analyst Portfolio
description: A Blog Portfolio created by Matt Lynnson E. Delgado
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Matt Lynnson E. Delgado
user_description: A licensed Electronics Engineer and an Aspiring Data Analyst. Looking for more progression and improvement
user_title: Data Analyst
email: Lynnson113@gmail.com
linkedin_username: Matt Lynnson E. Delgado 
github_username:  MLynnson
gplus_username:  

# Google-analytics
google-analytics:
  id: 

exclude: ['package.json', 'src' , 'node_modules']
